### PR TITLE
This adds SAMC21 support

### PR DESCRIPTION
**Pull request by prices**
This adds support for the SAMC21.

It requires the pull request that I put in on platform-atmelsam: https://github.com/platformio/platform-atmelsam/pull/22

Please let me know if you want something changed or fixed.

### CODE REVIEW

**Comment by ivankravets** [comment]
How about to use the separate CORE for SAMC? This PR will block updates for Arduino official Cores.

**Comment by prices** [comment]
I can certainly do that.  I didn't originally because there is a lot of duplicated code.

I will update the pull request when it is done.

**Comment by ivankravets** [comment]
Thanks! Please ping me here when you will be ready or need some help

**Comment by prices** [comment]
It actually occurred to me that it might be better to spend my time getting this code into the arduino SAM code.  Then it should automatically appear here.  I am going to pursue that, and I will get back to you if it doesn't work out.

Thanks!

**Comment by erikvanzijst** [comment]
I have a SAMC21 and I'm not entirely sure how to configure PlatformIO for it. I can only find the SAMD21 in PlatformIO and a Google search led me to this issue.

I'm entirely new to PlatformIO, so please forgive my ignorance, but seeing as this issue was closed and deferred to the Arduino cores, how do I go about programming my SAMC21?

**Pull request closed without merging**
